// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.time.Duration;
import java.util.*;

public class G1LoginLogoutTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tS0101_ts0102() throws InterruptedException {
        // Открыть главную страницу Mix
        driver.get("https://mix.com//");
        // Нажать на Apple авторизацию
        driver.findElement(By.xpath("(//form[contains(@action,'/auth/apple')]/button)[1]")).click();
        // Ручное заполнение данных
        Thread.sleep(30000);
        // Нажатие на иконку профиля
        driver.findElement(By.xpath("//div[@class='relative inline-block']/div/a")).click();
        // Нажатие на настройки
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//a[contains(@class,'btn-dot')]")));
            driver.findElement(By.xpath("//a[text()='Settings']")).click();
        }
        // Нажатие на Account Actions
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[text()='Account Actions']")));
            driver.findElement(By.xpath("//button[text()='Account Actions']")).click();
        }
        // Log out
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[text()='Log Out']")));
            driver.findElement(By.xpath("//button[text()='Log Out']")).click();
        }
        // Log out 2.0
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[contains(@class, 'bg-red-600')]")));
            driver.findElement(By.xpath("//button[contains(@class, 'bg-red-600')]")).click();
        }
        // Проверка что мы на главной странице
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[contains(@class, 'Home_animateFlyLongReverse__5u7eC') and not(contains(@class,'mt-16'))]")));
        }
    }

    @Test
    public void tS0103() throws InterruptedException {
        // Открыть главную страницу Mix
        driver.get("https://mix.com//");
        // Нажать на email авторизацию
        driver.findElement(By.xpath("(//button[contains(@class, 'btn-square') and not(contains(@class, 'focus:outline-none'))])[1]")).click();
        // Открытие окна
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[normalize-space()='Join Mix']")));
            assertThat(driver.findElement(By.xpath("//div[text()='Join Mix']")).getText(), is("Join Mix"));
        }
        // Вводим некорретный email
        driver.findElement(By.xpath("//input[@placeholder='Email address']")).sendKeys("test@ok.r");
        // Continue
        driver.findElement(By.xpath("//input[@type='submit']")).click();
        // Проверка появления ошибки
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[contains(@class, 'text-red-500')]")));
            assertThat(driver.findElement(By.xpath("//div[contains(@class, 'text-red-500')]")).getText(), is("Invalid email address. Please try again."));
        }
    }
}
