// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class G2Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tS0201StartExploring() {
        // Test name: TS-02-01. Начало просмотра через Start Exploring
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");
        // 2 | click | xpath=//button[normalize-space()='Start Exploring'] |
        driver.findElement(By.xpath("//button[normalize-space()=\'Start Exploring\']")).click();
        // 3 | waitForElementVisible | xpath=//button[normalize-space()='Next'] | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[normalize-space()=\'Next\']")));
        }
        // 4 | assertElementPresent | xpath=//img[@alt='Mix'] | 30000
        {
            List<WebElement> elements = driver.findElements(By.xpath("//img[@alt=\'Mix\']"));
            assert (elements.size() > 0);
        }
        // 5 | assertElementPresent | xpath=//button[normalize-space()='Next'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button[normalize-space()=\'Next\']"));
            assert (elements.size() > 0);
        }
        // 6 | assertElementNotPresent | xpath=//h1[normalize-space()='Expand your mind'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//h1[normalize-space()=\'Expand your mind\']"));
            assert (elements.size() == 0);
        }
    }

    @Test
    public void tS0202() {
        // Test name: TS-02-02. Переход к следующему материалу
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");
        // 2 | click | xpath=//button[normalize-space()='Start Exploring'] |
        driver.findElement(By.xpath("//button[normalize-space()=\'Start Exploring\']")).click();
        // 3 | waitForElementVisible | xpath=//button[normalize-space()='Next'] | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[normalize-space()=\'Next\']")));
        }
        // 4 | executeScript | return window.location.href | oldUrl
        vars.put("oldUrl", js.executeScript("return window.location.href"));
        // 5 | click | xpath=//button[normalize-space()='Next'] |
        driver.findElement(By.xpath("//button[normalize-space()=\'Next\']")).click();
        // 6 | pause | 3000 |
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 7 | executeScript | return window.location.href | newUrl
        vars.put("newUrl", js.executeScript("return window.location.href"));
        // 8 | executeScript | return ${oldUrl} !== ${newUrl} | isChanged
        vars.put("isChanged", js.executeScript("return arguments[0] !== arguments[1]", vars.get("oldUrl"), vars.get("newUrl")));
        // 9 | assert | isChanged | true
        assertEquals(vars.get("isChanged").toString(), "true");
    }

    @Test
    public void tS0203() {
        // Test name: TS-02-03 Доступность элементов просмотра после перехода к материалу
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");
        // 2 | click | xpath=//button[normalize-space()='Start Exploring'] |
        driver.findElement(By.xpath("//button[normalize-space()=\'Start Exploring\']")).click();
        // 3 | waitForElementVisible | xpath=//button[normalize-space()='Next'] | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[normalize-space()=\'Next\']")));
        }
        // 4 | verifyElementPresent | xpath=//img[@alt='Mix'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//img[@alt=\'Mix\']"));
            assert (elements.size() > 0);
        }
        // 5 | verifyElementPresent | xpath=//button[normalize-space()='Next'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button[normalize-space()=\'Next\']"));
            assert (elements.size() > 0);
        }
        // 6 | verifyElementPresent | xpath=//button[normalize-space()='Join Mix'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button[normalize-space()=\'Join Mix\']"));
            assert (elements.size() > 0);
        }
        // 7 | verifyElementPresent | xpath=//main//*[normalize-space()='Tags'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//main//*[normalize-space()=\'Tags\']"));
            assert (elements.size() > 0);
        }
        // 8 | verifyElementPresent | xpath=//button[.//div[contains(.,'Comments')]] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button[.//div[contains(.,\'Comments\')]]"));
            assert (elements.size() > 0);
        }
    }

    @Test
    public void tS0204() {
        // Test name: TS-02-04. Повторный последовательный переход к следующему материалу
        // Step # | name | target | value
        // 1 | open | https://mix.com/ |
        driver.get("https://mix.com/");
        // 2 | click | xpath=//button[normalize-space()='Start Exploring'] |
        driver.findElement(By.xpath("//button[normalize-space()=\'Start Exploring\']")).click();
        // 3 | waitForElementVisible | xpath=//button[normalize-space()='Next'] | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[normalize-space()=\'Next\']")));
        }
        // 4 | executeScript | return window.location.href | url1
        vars.put("url1", js.executeScript("return window.location.href"));
        // 5 | click | xpath=//button[normalize-space()='Next'] |
        driver.findElement(By.xpath("//button[normalize-space()=\'Next\']")).click();
        // 6 | executeScript | return window.location.href | url2
        vars.put("url2", js.executeScript("return window.location.href"));
        // 7 | click | xpath=//button[normalize-space()='Next'] |
        driver.findElement(By.xpath("//button[normalize-space()=\'Next\']")).click();
        // 8 | executeScript | return window.location.href | url3
        vars.put("url3", js.executeScript("return window.location.href"));
        // 9 | executeScript | return new Set([${url1}, ${url2}, ${url3}]).size === 3; | isDifferent
        vars.put("isDifferent", js.executeScript("return new Set([arguments[0], arguments[1], arguments[2]]).size === 3;", vars.get("url1"), vars.get("url2"), vars.get("url3")));
        // 10 | assert | isDifferent | true
        assertEquals("true", vars.get("isDifferent").toString());
    }
}
