// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.time.Duration;
import java.util.*;

public class G3Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tS0301_tS0302() throws InterruptedException {
        // Открываем материал
        driver.get("https://mix.com/!870259105913111552");
        //Закрыть окно, если оно есть
        //driver.findElement(By.xpath("//div[@id='close' and @aria-label='Закрыть']")).click();
        //Thread.sleep(500000);

        // Нажать на авторизацию
        driver.findElement(By.xpath("//button[text()='Join Mix']")).click();
        // Выбираем Apple
        driver.findElement(By.xpath("//button[./span[text()='Apple']]")).click();
        // Ручное заполнение данных
        Thread.sleep(30000);
        // Нажимаем Like
        driver.findElement(By.xpath("//div[./span[text()='Like (L)']]/button")).click();
        //Проверяем, что он стоит
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[./span[text()='Like (L)'] and ./button[contains(@class, 'opacity-100')]]")));
            Thread.sleep(5000);
        }
        // Нажимаем Like
        driver.findElement(By.xpath("//div[./span[text()='Like (L)']]/button")).click();
        //Проверяем, что он не стоит
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[./span[text()='Like (L)'] and ./button[contains(@class, 'opacity-50')]]")));
            Thread.sleep(5000);
        }
        // Нажимаем Disike
        driver.findElement(By.xpath("//div[./span[text()='Dislike (D)']]/button")).click();
        //Проверяем, что такого контента не будет
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[@role='status' and @aria-live='polite']")));
            assertThat(driver.findElement(By.xpath("//div[@role='status' and @aria-live='polite']")).getText(), is("You'll see less like that"));
            Thread.sleep(5000);
        }
    }
}
