// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.time.Duration;
import java.util.*;

public class G3Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tS0301Like() {
        // Открываем материал
        driver.get("https://mix.com/!870259105913111552");
        // Ждём кнопку Like
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".translate-x-0\\.5")));
        }
        // Нажимаем Like
        driver.findElement(By.cssSelector(".translate-x-0\\.5")).click();
        // Ждём обновления UI
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // Проверяем появление окна join mix
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".p-10"));
            assert (!elements.isEmpty());
        }
    }

    @Test
    public void tS0302Disike() {
        // Открываем материал
        driver.get("https://mix.com/!870259105913111552");
        // Ждём кнопку Like
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".-translate-x-0\\.5")));
        }
        // Нажимаем Like
        driver.findElement(By.cssSelector(".-translate-x-0\\.5")).click();
        // Ждём обновления UI
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // Проверяем появление окна join mix
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".p-10"));
            assert (!elements.isEmpty());
        }
    }

    @Test
    public void tS0303() throws InterruptedException {
        // Открываем материал
        driver.get("https://mix.com/!870259105913111552");
        // Ждём первый тег
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".btn-link:nth-child(1) > .flex")));
        }
        // Сохраняем текст тега
        String selectedTag = driver.findElement(By.cssSelector(".btn:nth-child(1) > .flex > .flex > span")).getText();
        // Переходим по тегу
        driver.findElement(By.cssSelector(".btn:nth-child(1) > .flex > .flex > span")).click();
        // Ждём загрузки (можно через WebDriverWait)
        Thread.sleep(2000); // или лучше WebDriverWait
        // Проверяем, что заголовок ленты соответствует выбранному тегу
        String feedHeader = driver.findElement(By.cssSelector(".text-3xl")).getText();
        // assert с реальной переменной
        assertThat(feedHeader, is(selectedTag));
    }

  public Map<String, Object> getVars() {
    return vars;
  }

  public void setVars(Map<String, Object> vars) {
    this.vars = vars;
  }
}
