// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class G4CommentsTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    private static final String BASE_URL = "https://mix.com/";

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        driver.manage().window().maximize();

        String authCookieValue = System.getenv("MIX_AUTH_COOKIE");
        if (authCookieValue == null || authCookieValue.isBlank()) {
            throw new IllegalStateException("MIX_AUTH_COOKIE is not set");
        }

        driver.get(BASE_URL);

        driver.manage().addCookie(
                new Cookie.Builder("intoprd", authCookieValue)
                        .domain("mix.com")
                        .path("/")
                        .isSecure(true)
                        .build()
        );

        driver.navigate().refresh();

        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tS0403CommentFormDisplayAuthorized() {
        // TS-04-03 Отображение формы комментария (авторизованный пользователь)

        openFirstMaterial();
        scrollToComments();

        // Проверяем, что нет предложения авторизоваться
        assertFalse(isElementPresent(By.xpath("//*[contains(normalize-space(),'Sign in to join the conversation')]")));

        // Проверяем, что есть форма/поле комментария
        WebElement commentInput = waitForAnyVisible(
                By.xpath("//textarea"),
                By.xpath("//div[@contenteditable='true']"),
                By.xpath("//textarea[contains(@placeholder,'comment') or contains(@placeholder,'Comment')]"),
                By.xpath("//textarea[contains(@placeholder,'conversation') or contains(@placeholder,'Conversation')]")
        );

        assertTrue(commentInput.isDisplayed());
    }

    @Test
    public void tS0404CommentInput() {
        // TS-04-04 Ввод комментария

        openFirstMaterial();
        scrollToComments();

        WebElement commentInput = waitForAnyVisible(
                By.xpath("//textarea"),
                By.xpath("//div[@contenteditable='true']"),
                By.xpath("//textarea[contains(@placeholder,'comment') or contains(@placeholder,'Comment')]"),
                By.xpath("//textarea[contains(@placeholder,'conversation') or contains(@placeholder,'Conversation')]")
        );

        String commentText = "Autotest comment input " + System.currentTimeMillis();
        typeIntoCommentField(commentInput, commentText);

        String actualText = getCommentFieldText(commentInput);
        assertTrue(actualText.contains(commentText));
    }

    @Test
    public void tS0405SendComment() {
        // TS-04-05 Отправка комментария

        openFirstMaterial();
        scrollToComments();

        WebElement commentInput = waitForAnyVisible(
                By.xpath("//textarea"),
                By.xpath("//div[@contenteditable='true']"),
                By.xpath("//textarea[contains(@placeholder,'comment') or contains(@placeholder,'Comment')]"),
                By.xpath("//textarea[contains(@placeholder,'conversation') or contains(@placeholder,'Conversation')]")
        );

        String commentText = "Autotest send comment " + System.currentTimeMillis();
        typeIntoCommentField(commentInput, commentText);

        WebElement submitButton = waitForAnyClickable(
                By.xpath("//button[@type='submit']"),
                By.xpath("//button[normalize-space()='Post']"),
                By.xpath("//button[normalize-space()='Comment']"),
                By.xpath("//button[normalize-space()='Send']"),
                By.xpath("//button[contains(.,'Post')]"),
                By.xpath("//button[contains(.,'Comment')]")
        );

        submitButton.click();

        // Проверяем, что комментарий появился в списке
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
        wait.until(ExpectedConditions.visibilityOfElementLocated(
                By.xpath("//*[contains(normalize-space(),\"" + commentText + "\")]")
        ));

        assertTrue(isElementPresent(By.xpath("//*[contains(normalize-space(),\"" + commentText + "\")]")));
    }

    @Test
    public void tS0406PublishedCommentDisplayedAsAuthor() {
        // TS-04-06 Отображение опубликованного комментария автора

        openFirstMaterial();
        scrollToComments();

        WebElement commentInput = waitForAnyVisible(
                By.xpath("//textarea"),
                By.xpath("//div[@contenteditable='true']"),
                By.xpath("//textarea[contains(@placeholder,'comment') or contains(@placeholder,'Comment')]"),
                By.xpath("//textarea[contains(@placeholder,'conversation') or contains(@placeholder,'Conversation')]")
        );

        String commentText = "Autotest author comment " + System.currentTimeMillis();
        typeIntoCommentField(commentInput, commentText);

        WebElement submitButton = waitForAnyClickable(
                By.xpath("//button[@type='submit']"),
                By.xpath("//button[normalize-space()='Post']"),
                By.xpath("//button[normalize-space()='Comment']"),
                By.xpath("//button[normalize-space()='Send']"),
                By.xpath("//button[contains(.,'Post')]"),
                By.xpath("//button[contains(.,'Comment')]")
        );

        submitButton.click();

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
        wait.until(ExpectedConditions.visibilityOfElementLocated(
                By.xpath("//*[contains(normalize-space(),\"" + commentText + "\")]")
        ));

        // Проверяем, что новый комментарий есть в списке
        assertTrue(isElementPresent(By.xpath("//*[contains(normalize-space(),\"" + commentText + "\")]")));
    }

    @Test
    public void tS0407ViewCommentsAuthorized() {
        // TS-04-07 Просмотр комментариев авторизованным пользователем

        openFirstMaterial();
        scrollToComments();

        // Проверяем наличие блока комментариев / списка комментариев
        boolean commentsVisible =
                isElementPresent(By.xpath("//*[contains(normalize-space(),'Comments')]")) ||
                        isElementPresent(By.xpath("//section[.//*[contains(normalize-space(),'Comments')]]")) ||
                        isElementPresent(By.xpath("//div[.//*[contains(normalize-space(),'Comments')]]")) ||
                        isElementPresent(By.xpath("//article[.//*[contains(normalize-space(),'Comments')]]"));

        assertTrue(commentsVisible);
    }

    /**
     * открытие первого тиктока
     */
    private void openFirstMaterial() {
        driver.get(BASE_URL);

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));

        WebElement startButton = wait.until(
                ExpectedConditions.elementToBeClickable(
                        By.xpath("//button[normalize-space()='Start Exploring']")
                )
        );
        startButton.click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(
                By.xpath("//button[normalize-space()='Next']")
        ));
    }

    private void scrollToComments() {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));

        By commentsBlock = By.xpath("//*[contains(normalize-space(),'Comments') or contains(normalize-space(),'Join the conversation')]");
        WebElement commentsElement = wait.until(ExpectedConditions.presenceOfElementLocated(commentsBlock));

        js.executeScript("arguments[0].scrollIntoView({block: 'center'});", commentsElement);

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    private WebElement waitForAnyVisible(By... locators) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));

        for (By locator : locators) {
            try {
                return wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
            } catch (TimeoutException ignored) {
            }
        }
        throw new NoSuchElementException("None of the target elements became visible");
    }

    private WebElement waitForAnyClickable(By... locators) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));

        for (By locator : locators) {
            try {
                return wait.until(ExpectedConditions.elementToBeClickable(locator));
            } catch (TimeoutException ignored) {
            }
        }
        throw new NoSuchElementException("None of the target elements became clickable");
    }

    private boolean isElementPresent(By locator) {
        List<WebElement> elements = driver.findElements(locator);
        return !elements.isEmpty();
    }

    private void typeIntoCommentField(WebElement element, String text) {
        String tagName = element.getTagName().toLowerCase();

        if ("textarea".equals(tagName) || "input".equals(tagName)) {
            element.click();
            element.clear();
            element.sendKeys(text);
        } else {
            element.click();
            element.sendKeys(Keys.chord(Keys.CONTROL, "a"));
            element.sendKeys(Keys.DELETE);
            element.sendKeys(text);
        }
    }

    private String getCommentFieldText(WebElement element) {
        String tagName = element.getTagName().toLowerCase();

        if ("textarea".equals(tagName) || "input".equals(tagName)) {
            return element.getAttribute("value");
        }
        return element.getText();
    }
}