// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;

public class G4CommentsGuestTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    //Попытка комментария (гость)
    @Test
    public void tS0401() {
        // Test name: TS-04-01 Попытка комментария (гость)
        // Step # | name | target | value
        // 1 | open | https://mix.com/ |
        driver.get("https://mix.com/");
        // 2 | click | xpath=//button[normalize-space()='Start Exploring'] |
        driver.findElement(By.xpath("//button[normalize-space()=\'Start Exploring\']")).click();
        // 3 | waitForElementVisible | xpath=//button[normalize-space()='Next'] | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[normalize-space()=\'Next\']")));
        }
        // 4 | click | xpath=//button[normalize-space()='Join the conversation'] |
        driver.findElement(By.xpath("//button[normalize-space()=\'Join the conversation\']")).click();
        // 5 | verifyElementPresent | xpath=//div[normalize-space()='Sign in to join the conversation'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[normalize-space()=\'Sign in to join the conversation\']"));
            assert (elements.size() > 0);
        }
        // 6 | verifyElementPresent | xpath=//button[@aria-label='Close modal'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button[@aria-label=\'Close modal\']"));
            assert (elements.size() > 0);
        }
        // 7 | verifyElementPresent | xpath=//button/span[normalize-space()='Email'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button/span[normalize-space()=\'Email\']"));
            assert (elements.size() > 0);
        }
    }

    //Отображение комментариев
    @Test
    public void tS0402() {
        // Test name: TS-04-02 Отображение комментариев
        // Step # | name | target | value
        // 1 | open | https://mix.com/ |
        driver.get("https://mix.com/");
        // 2 | click | xpath=//button[normalize-space()='Start Exploring'] |
        driver.findElement(By.xpath("//button[normalize-space()=\'Start Exploring\']")).click();
        // 3 | waitForElementVisible | xpath=//button[normalize-space()='Next'] | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[normalize-space()=\'Next\']")));
        }
        // 4 | assertElementPresent | xpath=//button[.//div[contains(.,'Comments')]] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button[.//div[contains(.,\'Comments\')]]"));
            assert (elements.size() > 0);
        }
        // 4.5 - скролл до коментов
        WebElement element = driver.findElement(
                By.xpath("//button[.//div[contains(.,'Comments')]]")
        );

        // скроллим
        ((JavascriptExecutor) driver).executeScript(
                "arguments[0].scrollIntoView({block: 'center'});",
                element
        );
        // 5 | click | xpath=//button[.//div[contains(.,'Comments')]] |
        // Нажатие (разворачивание) коментов
//        element.click();
        // 6 | assertElementPresent | xpath=//div[contains(@class,'overflow-y-scroll') and contains(@class,'space-y-4')] |
        // Проверка видимости бокса с комментариями
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[contains(@class,\'overflow-y-scroll\') and contains(@class,\'space-y-4\')]"));
            assert (elements.size() > 0);
        }
        // 7 | click | xpath=//button[.//div[contains(.,'Comments')]] |
        // Нажатие (сворачивание) коментов
        driver.findElement(By.xpath("//button[.//div[contains(.,\'Comments\')]]")).click();
        // 8 | assertElementNotPresent | xpath=//div[@class='space-y-4 overflow-y-scroll scrollbar-hide p-2']/* |
        // Проверка что в боксе с коментами ничего нет после сворачивания
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[@class=\'space-y-4 overflow-y-scroll scrollbar-hide p-2\']/*"));
            assert (elements.size() == 0);
        }
    }
}
