// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import utils.AuthSetup;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class G4CommentsAuthTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    private static final String BASE_URL = "https://mix.com/";
    private static final String COMMENT_INPUT_XPATH = "//input[@type='text' and (contains(@placeholder,'Add a comment...') or contains(@placeholder,'Be the first to comment...'))]";

    @Before
    public void setUp() {
        driver = AuthSetup.createAuthorizedDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tS0403CommentFormDisplayAuthorized() {
        // TS-04-03 Отображение формы комментария для авторизованного

//        openFirstMaterial();
        scrollToComments();

        // Проверяем, что нет предложения авторизоваться
        assertFalse(isElementPresent(By.xpath("//*[contains(normalize-space(),'Sign in to join the conversation')]")));

        // Проверяем, что есть форма/поле комментария
        WebElement commentInput = waitForAnyVisible(
                By.xpath(COMMENT_INPUT_XPATH)
        );

        assertTrue(commentInput.isDisplayed());
    }

    @Test
    public void tS0404CommentInput() {
        // TS-04-04 Ввод комментария

//        openFirstMaterial();
        scrollToComments();

        WebElement commentInput = waitForAnyVisible(
                By.xpath(COMMENT_INPUT_XPATH)
        );

        String commentText = "супер🥶🐒🥰 " + System.currentTimeMillis();
        typeIntoCommentField(commentInput, commentText);

        String actualText = commentInput.getAttribute("value");
        assertTrue(actualText.contains(commentText));
    }

    @Test
    public void tS0405SendComment() {
        // TS-04-05 Отправка комментария

//        openFirstMaterial();
        scrollToComments();

        WebElement commentInput = waitForAnyVisible(
                By.xpath(COMMENT_INPUT_XPATH)
        );

        String commentText = "вау😩🏳️‍🌈🥰 " + System.currentTimeMillis();
        typeIntoCommentField(commentInput, commentText);

        commentInput.sendKeys(Keys.ENTER);

        // Проверяем, что комментарий появился в списке
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
        wait.until(ExpectedConditions.visibilityOfElementLocated(
                By.xpath("//*[contains(normalize-space(),'" + commentText + "')]")
        ));

        assertTrue(isElementPresent(By.xpath("//*[contains(normalize-space(),\"" + commentText + "\")]")));
    }

    @Test
    public void tS0406PublishedCommentDisplayedAsAuthor() {
        // TS-04-06 Отображение опубликованного комментария автора

//        openFirstMaterial();
        scrollToComments();

        WebElement commentInput = waitForAnyVisible(
                By.xpath(COMMENT_INPUT_XPATH)
        );

        String commentText = "эмейзинг♿🤢🦍 " + System.currentTimeMillis();
        typeIntoCommentField(commentInput, commentText);

        commentInput.sendKeys(Keys.ENTER);

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
        wait.until(ExpectedConditions.visibilityOfElementLocated(
                By.xpath("//*[contains(normalize-space(),\"" + commentText + "\")]")
        ));

        // Проверяем, что новый комментарий есть в списке
        assertTrue(isElementPresent(By.xpath("//*[contains(normalize-space(),\"" + commentText + "\")]")));
    }

    @Test
    public void tS0407ViewCommentsAuthorized() {
        // TS-04-07 Просмотр комментариев авторизованным пользователем

//        openFirstMaterial();
        scrollToComments();

        // Проверяем наличие блока комментариев / списка комментариев
        boolean commentsVisible =
                isElementPresent(By.xpath("//div[contains(@class,'overflow-y-scroll') and contains(@class,'space-y-4')]"));

        assertTrue(commentsVisible);
    }

    /**
     * открытие первого тиктока
     */
    private void openFirstMaterial() {
        driver.get(BASE_URL);

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));

        WebElement startButton = wait.until(
                ExpectedConditions.elementToBeClickable(
                        By.xpath("//button[normalize-space()='Start Exploring']")
                )
        );
        startButton.click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(
                By.xpath("//button[normalize-space()='Next']")
        ));
    }

    private void scrollToComments() {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));

        By commentsInput = By.xpath(COMMENT_INPUT_XPATH);
        WebElement commentsElement = wait.until(ExpectedConditions.presenceOfElementLocated(commentsInput));

        js.executeScript("arguments[0].scrollIntoView({block: 'center'});", commentsElement);

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    private WebElement waitForAnyVisible(By... locators) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));

        for (By locator : locators) {
            try {
                return wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
            } catch (TimeoutException ignored) {
            }
        }
        throw new NoSuchElementException("не вижу");
    }

    private WebElement waitForAnyClickable(By... locators) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));

        for (By locator : locators) {
            try {
                return wait.until(ExpectedConditions.elementToBeClickable(locator));
            } catch (TimeoutException ignored) {
            }
        }
        throw new NoSuchElementException("не кликается (нет такого)");
    }

    private boolean isElementPresent(By locator) {
        List<WebElement> elements = driver.findElements(locator);
        return !elements.isEmpty();
    }

    private void typeIntoCommentField(WebElement element, String text) {
        element.click();
        element.clear();
        element.sendKeys(text);
    }
}