// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class G5Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tS0501TS0502() throws InterruptedException {
        // Открыть главную страницу Mix
        driver.get("https://mix.com//");
        // Нажать на Apple авторизацию
        driver.findElement(By.xpath("(//form[contains(@action,'/auth/apple')]/button)[1]")).click();
        // Ручное заполнение данных
        Thread.sleep(30000);
        // Нажатие на поиск
        driver.findElement(By.xpath("//a[contains(@class, 'sm:block')]")).click();
        // Поиск профиля
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[contains(@class, 'h-fit')]")));
            driver.findElement(By.xpath("//input[contains(@class, 'h-fit')]")).sendKeys("@55e5d");
        }
        // Подписаться
        driver.findElement(By.xpath("//div[contains(@class, 'z-20')]/button")).click();
        // Проверка подписки
        {
            WebDriverWait wait1 = new WebDriverWait(driver, Duration.ofSeconds(5));
            wait1.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[contains(@class, 'z-20')]/button[contains(@class, 'btn-secondary')]")));
        }
        // Отписаться
        driver.findElement(By.xpath("//div[contains(@class, 'z-20')]/button")).click();
        // Проверка отписки
        {
            WebDriverWait wait2 = new WebDriverWait(driver, Duration.ofSeconds(5));
            wait2.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[contains(@class, 'z-20')]/button[not(contains(@class, 'btn-secondary'))]")));
        }
    }

    @Test
    public void tS0503TS0504() throws InterruptedException {
        // Открыть материал
        driver.get("https://mix.com/topic/guitars");
        // Нажать на подписку
        driver.findElement(By.xpath("//button[contains(@class, 'btn-primary') and text()='Follow']")).click();
        // Зайти через Apple
        driver.findElement(By.xpath("//button[./span[text()='Apple']]")).click();
        // Ручное заполнение данных
        Thread.sleep(30000);
        // Нажать на подписку
        driver.findElement(By.xpath("//button[contains(@class, 'btn-primary') and text()='Follow']")).click();
        // проверка что подписка есть
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[contains(@class, 'btn-primary') and text()='Following']")));
        }
        // Отписаться
        driver.findElement(By.xpath("//button[contains(@class, 'btn-primary') and text()='Following']")).click();
        // Проверка отписки
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[contains(@class, 'btn-primary') and text()='Follow']")));
        }
    }
}
