// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;

public class G6Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tS0601() {
        // Открываем материал
        driver.get("https://mix.com//!870259105913111552");
        // Проверка о наличие окна тегов
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[text()='Tags']")));
        }
    }

    @Test
    public void tS0602() throws InterruptedException {
        // Открываем материал
        driver.get("https://mix.com/!870259105913111552");
        // Сохраняем текст тега
        String selectedTag = driver.findElement(By.xpath("(//a[contains(@class, 'btn-link') and contains(@class, 'mb-1.5')]/div/div/span)[1]")).getText();
        // Переходим по тегу
        driver.findElement(By.xpath("(//a[contains(@class, 'btn-link') and contains(@class, 'mb-1.5')])[1]")).click();
        // Проверяем, что заголовок ленты соответствует выбранному тегу
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//p[contains(@class, 'text-3xl')]")));
            assertThat(driver.findElement(By.xpath("//p[contains(@class, 'text-3xl')]")).getText(), is(selectedTag));
        }
    }

    @Test
    public void tS0603() throws InterruptedException {
        // Открываем тег
        driver.get("https://mix.com//topic/guitars");
        // Сохраняем текст тега
        String selectedTag = driver.findElement(By.xpath("//p[contains(@class, 'text-3xl')]")).getText();
        // Переходим по первой публикации в подборке
        driver.findElement(By.xpath("(//div[contains(@class, 'xblock')]/div/div/a)[1]")).click();
        Thread.sleep(3000);
        // Проверка что такой тег существует
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//a[contains(@class, 'btn-link') and contains(@class, 'mb-1.5')]/div/div/span)"));
            boolean found = false;
            for (WebElement element : elements) {
                if (element.getText().equals(selectedTag)) {
                    found = true;
                    break;
                }
            }
            assert found;
        }
    }
}
