// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;

public class G7AuthVariantsTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tS0700() {
        // Test name: TS-07-00. Отображение способов входа
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");
        // 2 | verifyElementPresent | xpath=//div[@aria-label='Войти с аккаунтом Google (откроется в новой вкладке)'] |
        // проверка google
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[@aria-label=\'Войти с аккаунтом Google (откроется в новой вкладке)\']"));
            assert (elements.size() > 0);
        }
        // 3 | verifyElementPresent | xpath=(//form[contains(@action,'/auth/facebook')])[1] |
        // проверка facebook
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//form[contains(@action,\'/auth/facebook\')])[1]"));
            assert (elements.size() > 0);
        }
        // 4 | verifyElementPresent | xpath=(//form[contains(@action,'/auth/twitter')])[1] |
        // проверка твитера
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//form[contains(@action,\'/auth/twitter\')])[1]"));
            assert (elements.size() > 0);
        }
        // 5 | verifyElementPresent | xpath=(//form[contains(@action,'/auth/apple')])[1] |
        // проверка яблока
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//form[contains(@action,\'/auth/apple\')])[1]"));
            assert (elements.size() > 0);
        }
        // 6 | verifyElementPresent | xpath=(//button[contains(@class, 'btn-square') and not(contains(@class, 'focus:outline-none'))])[1] |
        // првоерка через почту
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//button[contains(@class, \'btn-square\') and not(contains(@class, \'focus:outline-none\'))])[1]"));
            assert (elements.size() > 0);
        }
    }

    @Test
    public void tS0701Google() {
        // Test name: TS-07-01. Проверка открытия окна при входе с Google с главной
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");

        // 3 | click | xpath=//div[@aria-label='Войти с аккаунтом Google (откроется в новой вкладке)'] |
        By googleBtn = By.xpath("//div[@aria-label=\'Войти с аккаунтом Google (откроется в новой вкладке)\']");

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
        wait.until(ExpectedConditions.elementToBeClickable(googleBtn));

        String originalWin = driver.getWindowHandle();
        Set<String> allOldWins = driver.getWindowHandles();

        driver.findElement(googleBtn).click();

        wait.until(driver -> driver.getWindowHandles().size() > allOldWins.size());

        Set<String> allWindows = driver.getWindowHandles();
        String newWindow = null;

        for (String handle : allWindows) {
            if (!allOldWins.contains(handle)) {
                newWindow = handle;
                break;
            }
        }

        driver.switchTo().window(newWindow);

        wait.until(d -> {
            String url = d.getCurrentUrl();
            return url != null && !url.isBlank() && !"about:blank".equals(url);
        });

        String newWindowUrl = driver.getCurrentUrl();

        assertTrue(
                "Ожидался переход на Google OAuth, но URL был: " + newWindowUrl,
                newWindowUrl.toLowerCase().contains("google")
        );
    }

    @Test
    public void tS0702facebook() {
        // Test name: TS-07-02. Проверка открытия окна при входе с facebook с главной
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");
        // 2 | storeWindowHandle | win0 |
        vars.put("win0", driver.getWindowHandle());
        // 3 | click | xpath=(//form[contains(@action,'/auth/facebook')])[1]//button |
        driver.findElement(By.xpath("(//form[contains(@action,\'/auth/facebook\')])[1]//button")).click();
        // 4 | assertElementPresent | xpath=(//form[contains(@action,'/auth/facebook')])[1]//button |
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//form[contains(@action,\'/auth/facebook\')])[1]//button"));
            assert (elements.size() > 0);
        }
        // 5 | click | xpath=(//form[contains(@action,'/auth/facebook')])[1]//button |
        driver.findElement(By.xpath("(//form[contains(@action,\'/auth/facebook\')])[1]//button")).click();
    }

    @Test
    public void tS0703X() {
        // Test name: TS-07-03. Проверка открытия окна при входе с X с главной
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");
        // 2 | storeWindowHandle | win0 |
        vars.put("win0", driver.getWindowHandle());
        // 3 | click | xpath=(//form[contains(@action,'/auth/twitter')])[1]//button |
        driver.findElement(By.xpath("(//form[contains(@action,\'/auth/twitter\')])[1]//button")).click();
        // 4 | assertElementPresent | xpath=(//form[contains(@action,'/auth/twitter')])[1]//button |
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//form[contains(@action,\'/auth/twitter\')])[1]//button"));
            assert (elements.size() > 0);
        }
        // 5 | click | xpath=(//form[contains(@action,'/auth/twitter')])[1]//button |
        driver.findElement(By.xpath("(//form[contains(@action,\'/auth/twitter\')])[1]//button")).click();
    }

    @Test
    public void tS0705() {
        // Test name: TS-07-05. Проверка открытия окна при входе с почтой с главной
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");
        // 2 | storeWindowHandle | win0 |
        vars.put("win0", driver.getWindowHandle());
        // 3 | click | xpath=(//button[contains(@class, 'btn-square') and not(contains(@class, 'focus:outline-none'))])[1] |
        driver.findElement(By.xpath("(//button[contains(@class, \'btn-square\') and not(contains(@class, \'focus:outline-none\'))])[1]")).click();
        // 4 | assertElementPresent | xpath=(//button[contains(@class, 'btn-square') and not(contains(@class, 'focus:outline-none'))])[1] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//button[contains(@class, \'btn-square\') and not(contains(@class, \'focus:outline-none\'))])[1]"));
            assert (elements.size() > 0);
        }
        // 5 | click | xpath=(//button[contains(@class, 'btn-square') and not(contains(@class, 'focus:outline-none'))])[1] |
        By emailBtn = By.xpath("(//button[contains(@class,'btn-square') and not(contains(@class,'focus:outline-none'))])[1]");
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));

        WebElement button = wait.until(ExpectedConditions.visibilityOfElementLocated(emailBtn));
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView({block: 'center'});", button);
        ((JavascriptExecutor) driver).executeScript("arguments[0].click();", button);
        // 6 | verifyElementPresent | xpath=//div[normalize-space()='Join Mix'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[normalize-space()=\'Join Mix\']"));
            assert (elements.size() > 0);
        }
        // 7 | verifyElementPresent | xpath=//input[@name='email' and @placeholder='Email address'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//input[@name=\'email\' and @placeholder=\'Email address\']"));
            assert (elements.size() > 0);
        }
        // 8 | verifyElementPresent | xpath=//input[@type='submit' and @value='Continue'] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//input[@type=\'submit\' and @value=\'Continue\']"));
            assert (elements.size() > 0);
        }
    }

    @Test
    public void tS0704apple() {
        // Test name: TS-07-04. Проверка открытия окна при входе с apple с главной
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");
        // 2 | storeWindowHandle | win0 |
        vars.put("win0", driver.getWindowHandle());
        // 3 | click | xpath=(//form[contains(@action,'/auth/apple')])[1]//button |
        driver.findElement(By.xpath("(//form[contains(@action,\'/auth/apple\')])[1]//button")).click();
        // 4 | assertElementPresent | xpath=(//form[contains(@action,'/auth/apple')])[1]//button |
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//form[contains(@action,\'/auth/apple\')])[1]//button"));
            assert (elements.size() > 0);
        }
        // 5 | click | xpath=(//form[contains(@action,'/auth/apple')])[1]//button |
        driver.findElement(By.xpath("(//form[contains(@action,\'/auth/apple\')])[1]//button")).click();
    }
}
