// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class G7Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tS0700() {
        // Test name: TS-07-00. Отображение способов входа
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");
        // 2 | verifyElementPresent | xpath=//div[@aria-label='Войти с аккаунтом Google (откроется в новой вкладке)'] |
        // проверка google
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[@aria-label=\'Войти с аккаунтом Google (откроется в новой вкладке)\']"));
            assert (elements.size() > 0);
        }
        // 3 | verifyElementPresent | xpath=(//form[contains(@action,'/auth/facebook')])[1] |
        // проверка facebook
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//form[contains(@action,\'/auth/facebook\')])[1]"));
            assert (elements.size() > 0);
        }
        // 4 | verifyElementPresent | xpath=(//form[contains(@action,'/auth/twitter')])[1] |
        // проверка твитера
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//form[contains(@action,\'/auth/twitter\')])[1]"));
            assert (elements.size() > 0);
        }
        // 5 | verifyElementPresent | xpath=(//form[contains(@action,'/auth/apple')])[1] |
        // проверка яблока
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//form[contains(@action,\'/auth/apple\')])[1]"));
            assert (elements.size() > 0);
        }
        // 6 | verifyElementPresent | xpath=(//button[contains(@class, 'btn-square') and not(contains(@class, 'focus:outline-none'))])[1] |
        // првоерка через почту
        {
            List<WebElement> elements = driver.findElements(By.xpath("(//button[contains(@class, \'btn-square\') and not(contains(@class, \'focus:outline-none\'))])[1]"));
            assert (elements.size() > 0);
        }
    }

    @Test
    public void tS0701Google() {
        // Test name: TS-07-01. Проверка открытия окна при входе с Google с главной
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://mix.com//");

        // 3 | click | xpath=//div[@aria-label='Войти с аккаунтом Google (откроется в новой вкладке)'] |
        By googleBtn = By.xpath("//div[@aria-label=\'Войти с аккаунтом Google (откроется в новой вкладке)\']");

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
        wait.until(ExpectedConditions.elementToBeClickable(googleBtn));

        String originalWin = driver.getWindowHandle();
        Set<String> allOldWins = driver.getWindowHandles();

        driver.findElement(googleBtn).click();

        wait.until(driver -> driver.getWindowHandles().size() > allOldWins.size());

        Set<String> allWindows = driver.getWindowHandles();
        String newWindow = null;

        for (String handle : allWindows) {
            if (!allOldWins.contains(handle)) {
                newWindow = handle;
                break;
            }
        }

        driver.switchTo().window(newWindow);

        wait.until(d -> {
            String url = d.getCurrentUrl();
            return url != null && !url.isBlank() && !"about:blank".equals(url);
        });

        String newWindowUrl = driver.getCurrentUrl();

        assertTrue(
                "Ожидался переход на Google OAuth, но URL был: " + newWindowUrl,
                newWindowUrl.toLowerCase().contains("google")
        );
    }
}
